### ISSUE TITLE
problems with library and serial example

### ISSUE THREAD

**Issue by pedcaval** [Lantronix/xpwJSlib#1]
I have working with xPico Wifi Shield a couple of days... I've just tested to send data from a MCU using serial 1 and everything goes ok.
Now i am testing serial port access via web. I've uploaded serial.html and xpwLib.js into http folder in the xPico. The MCU is conected in the Serial1 and it is working as an USB to TTL converter. Using a terminal i may send info to the xPICO through the MCU. Bytes received are increased in the xPico status line page but not in the serial.html example. I've tested it with Mozilla, IE and Chrome with the same result.
Perhaps, I am doing something wrong, would you mind to help me?

**Comment by mgolu** [comment]
By default the serial.html is looking for the minified version of the library (look at line 3). If you loaded xpwLib.js and not xpwLib-0.1.min.js to the xPico Wi-Fi's filesystem, then you need to change line 3 to look for the filename that you uploaded. Or put the minified version in there.

Once that's working, please make sure that Line 1 is set to protocol "None". This should be displayed at the top of the serial.html file.

If you still run into trouble, please run the debug tools in Chrome (Ctrl-Shift-I) and post the log of the transactions between the browser and the server.

**Comment by pedcaval** [comment]
Dear Mariano,

Thank you for your answer.

I debugged the network link and the ajax response from the server is ‘failed’.

I forgot to say you that my xPico firmware is 1.3.0.1R4… so I suppose that this would be the problem.

Anyway, I have attached the log in this mail.

Yours sincerely,

Pedro Catalan Valdelomar

**Comment by mgolu** [comment]
Hello Pedro,

Yes, this feature does require version 1.4 of firmware. That's still in Alpha, please contact your Lantronix sales or FAE to receive Alpha firmware to put on your xPico Wi-Fi.

Mariano
