### ISSUE TITLE
Mensajes rechazados

### ISSUE THREAD

**Issue by pedcaval** [Lantronix/xpwJSlib#2]

**Comment by mgolu** [comment]
Hola Pedro,
No me ha llegado tu email directamente. No se por qué están rechazados.
Puedes intentar otra vez?

Mariano

**Comment by pedcaval** [comment]
Hola Mariano,

Acabo de reenviarte el correo a tu dirección de mariano.goluboff@lantronix.com y me sigue saliendo que el correo ha sido rechazado por:

 

< <mailto:mariano.goluboff@lantronix.com> mariano.goluboff@lantronix.com>: host

    lantronix.com.inbound10.mxlogic.net[208.65.144.3] said: 554 Denied

    [73ba8c55.0.43918.00-2339.95883.p02c11m022.mxlogic.net] (Mode: normal) (in

    reply to end of DATA command)

 

Un saludo,

 

Pedro Catalan Valdelomar
departamento técnico

ARITHMETRICS, S.L.
C/ Musico Martinez Coll 2, pta. 14
46020 VALENCIA (SPAIN)

Tel: +34 692 04 99 82
Fax: +34 96 360 9190
email: pcatalan@arithmetrics.es

web: http://www.arithmetrics.es <http://www.arithmetrics.es/> 

 

Este correo electrónico está dirigido exclusivamente al destinatario o destinatarios especificados y la información contenida en él es confidencial y privilegiada, siendo el destinatario conocedor del carácter de la misma. Si ha recibido este mensaje por error, por favor notifíqueselo inmediatamente al remitente por correo electrónico y proceda a su eliminación de manera inmediata. Queda prohibido cualquier uso, revisión, difusión, distribución o copiado no autorizado de esta información, que, si se produjera, constituiría un incumplimiento de la confidencialidad. Las opiniones, conclusiones e información contenidas en este mensaje que no sean reconocidas oficialmente por la empresa Arithmetrics, S.L., no vincularán a la misma y se considerarán como no suministradas.

Muchas gracias por su colaboración.


This e-mail is intended only for its indicated address or addresses and the information contained in it is confidential and privileged, and you are on notice of its status. If you have received this e-mail in error please notify immediately the sender by reply e-mail and delete it immediately. Any use, review, dissemination, distribution or copying none authorised of this e mail is prohibited; to do so could be a breach of confidence. The opinions, conclusions and information in this message that have not been officially assumed by the Firm Arithmetrics, S.L., will not be binding to it, and will be understood as neither given.

Thank you for your co-operation.

 

De: Mariano Goluboff [mailto:notifications@github.com] 
Enviado el: lunes, 10 de agosto de 2015 15:43
Para: Lantronix/xpwJSlib
CC: pedcaval
Asunto: Re: [xpwJSlib] Mensajes rechazados (#2)

 

Hola Pedro,
No me ha llegado tu email directamente. No se por qué están rechazados.
Puedes intentar otra vez?

Mariano
